modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/ldtteam/Structurize/issues/new" #optional
license="MIT"
[[mods]] #mandatory
modId="animatrix" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Animatrix" #mandatory
credits="Every coffee anyone has drank!" #optional
authors="LDT Team" #optional
description='''
Animatrix is a mod for the famous game Minecraft from Mojang.
This mod allows the use of Skeleton based rendering and animations for Entities.
It allows modder to use custom and beautifull animations and models created outside of the usual Minecraft programming paradigms, like with forexample Blender, and export those models and Animations to Collada, for use inside the Minecraft game engine.
'''
[[dependencies.animatrix]]
    modId="graphicsexpanded"
    mandatory=true
    versionRange="[0.10,)"
    ordering="AFTER"
    side="CLIENT"